version: "3.5"
services:
  gitlab:
    container_name: gitlab
    build:
      context: ./gitlab
    hostname: gitlab
    restart: always
    volumes:
      - /config:/etc/gitlab
      - /logs:/var/log/gitlab
      - /data:/var/opt/gitlab
  artifactory:
    container_name: artifactory
    restart: always
    build:
      context: ./artifactory
    hostname: artifactory
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
#  jenkins-docker:
#    container_name: jenkins-docker
#    image: docker:dind
#    hostname: jenkins
#    privileged: True
#    environment: 
#      - DOCKER_TLS_CERTDIR=/certs
#    volumes:
#      - jenkins-docker-certs:/certs/client
#      - jenkins-data:/var/jenkins_home
#  jenkins-master:
#    container_name: jenkins-master
#    hostname: jenkins-master
#    build:
#      context: ./jenkins-image
#    networks:
#      jenkins:
#    environment:
#      - DOCKER_HOST=tcp://docker:2376
#      - DOCKER_CERT_PATH=/certs/client
#      - DOCKER_TLS_VERIFY=1
#    ports:
#      - 8080:8080
#      - 50000:50000
#    volumes:
#      - jenkins-data:/var/jenkins_home
#      - jenkins-docker-certs:/certs/client:ro
#  jenkins-linux-agent:
#    container_name: jenkins-linux-agent
#    hostname: jenkins-linux-x64
#    build:
#      context: ./jenkins-linux-image
#    networks:
#      jenkins:
  gitlab-runner-docker:
    container_name: gitlab-runner-docker
    hostname: gitlab-runner-docker
    restart: always
    depends_on:
      - gitlab
    build:
      context: ./gitlab-runner-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  artifactory_data:
    driver: local
  jenkins-docker-certs:
    driver: local
  jenkins-data:
    driver: local
      