concurrent = 4
check_interval = 0
shutdown_timeout = 0

[session_server]
  listen_address = "[::]:8088"
  session_timeout = 1800

[[runners]]
  name = "linux-x64"
  url = "http://gitlab/"
  id = 1
  token = "DgcrncCrjhVzZWJeREks"
  token_obtained_at = 2022-12-24T15:12:28Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  pre_clone_script = "git config --global --add safe.directory $CI_PROJECT_DIR"
  post_clone_script = "git config --global --add safe.directory $(pwd)"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    pull_policy = "if-not-present"
    network_mode = "docker_default"
